== Setup
anchor:sec-setup[Setup]

:workingdir: lis-public-testcases

WARNING: If you have not set up your computing environment to compile and run the LISF code, review the {url-official-docs}[official documentation,window=_blank].

=== Create a working directory

To begin, create and step into a working directory that you will use throughout the testcases. This directory will be referred to as `$WORKING_DIR` from this point forward. In the following example, the working directory is called `{workingdir}`:

[#create-workingdir]
[source,shell,subs="attributes"]
----
% mkdir {workingdir}
% cd {workingdir}
----

=== Clone the LISF Source Code Repository

While inside your `$WORKING_DIR` use `git` to clone the LISF repository:

[#clone-lis]
[source,shell,subs="attributes"]
----
% git clone https://github.com/NASA-LIS/LISF.git
----

Change directories into `LISF/` using `cd LISF`.

Use `git` again to check out commit {url-rev-commit}[{rev-commit}], a snapshot of the code known to be compatible with these testcases (_as of {revdate}_).

[#checkout-commit]
[source,shell,subs="attributes"]
----
% git checkout {rev-commit}
----

=== Configure and Compile the LISF Components

For information about configuration settings and detailed compilation instructions, see the {url-official-docs}[official documentation,window=_blank]. In general, the compilation process for each component is as follows:

.For LDT:
[#compile-ldt]
[source,shell,subs="attributes"]
----
% cd ldt
% ./configure
> # Select compile configuration settings (see Docs)...
% ./compile
> # Compilation output...
% mv LDT ../../            # move executable up into $WORKING_DIR
% cd ..                    # change directories back into LISF
----

.For LIS:
[#compile-lis]
[source,shell,subs="attributes"]
----
% cd lis
% ./configure
> # Select compile configuration settings (see Docs)...
% ./compile
> # Compilation output...
% mv LIS ../../            # move executable up into $WORKING_DIR
% cd ..                    # change directories back into LISF
----

.For LVT:
[#compile-lvt]
[source,shell,subs="attributes"]
----
% cd lvt
% ./configure
> # Select compile configuration settings (see Docs)...
% ./compile
> # Compilation output...
% mv LVT ../../            # move executable up into $WORKING_DIR
% cd ..                    # change directories back into LISF
----

Your `$WORKING_DIR` should now contain three executable files: `LDT`, `LIS`, `LVT`. You are ready to run the testcases.