== Setup
anchor:sec_setup[Setup]

:workingdir: lis-public-testcases

WARNING: If you have not set up your computing environment to compile and run the LISF code, review the {url-official-docs}[official documentation].

=== Create a working directory

To begin, create and step into a working directory that you will use throughout the testcases. This directory will be referred to as `$WORKING_DIR` from this point forward. In the following example, the working directory is called `{workingdir}`:

[#create-workingdir]
[source,bash,subs="attributes"]
----
% mkdir {workingdir}
% cd {workingdir}
----

=== Clone the LISF Source Code Repository

While inside your `$WORKING_DIR` use `git` to clone the LISF repository:

[#clone-lis]
[source,bash,subs="attributes"]
----
% git clone https://github.com/NASA-LIS/LISF.git
----

Change directories into `LISF/` using `cd LISF`.

Use `git` again to check out commit {url-rev-commit}[{rev-commit}], a snapshot of the code known to be compatible with these testcases (_as of {revdate}_).

[#checkout-commit]
[source,bash,subs="attributes"]
----
% git checkout {rev-commit}
----

=== Configure and Compile the LISF Components

For information about configuration settings and detailed compilation instructions, see the {url-official-docs}[official documentation]. In general, the compilation process for each component is as follows:

.For LDT:
[#compile-ldt]
[source,bash,subs="attributes"]
----
% cd ldt
% ./configure
# Select compilation configuration settings (see Docs)
% ./compile
# Compilation output...
% cd .. # change directories back into LISF
----

.For LIS:
[#compile-lis]
[source,bash,subs="attributes"]
----
% cd lis
% ./configure
# Select compilation configuration settings (see Docs)
% ./compile
# Compilation output...
% cd .. # change directories back into LISF
----

.For LVT:
[#compile-lvt]
[source,bash,subs="attributes"]
----
% cd lvt
% ./configure
# Select compilation configuration settings (see Docs)
% ./compile
# Compilation output...
% cd .. # change directories back into LISF
----

The `LISF/` directory should now contain three executable files: `LDT`, `LIS`, `LVT`. Use `mv` to move each of these executable files up into your `$WORKING_DIR`:

[#move-executables]
[source,bash,subs="attributes"]
----
% mv LDT LIS LVT ..
----

You are now ready to run the testcases.