== {title_step1}
anchor:sec_step1[{title_step1}]

=== Overview

In this step you will learn how to...

* Run LDT
* Perform parameter processing for the Noah-3.6 land surface model (LSM)
* Generate a Noah-3.6 parameter input file to be used in later steps by LIS (and LVT)

NOTE: These testcases were designed to be run in sequential order and later steps require the output generated by earlier steps.

==== Steps to Running LDT

1. Create LDT executable (see *<<sec_setup>>*)
2. Modify `ldt.config` file to define runtime configuration settings
3. Run the LDT executable
4. Examine output

==== Files Generated by an LDT Parameter Processing Run

The following files are typically generated by an LDT parameter processing run. This type of run is used to create the files required to run LIS.

* `lis_input.d01.nc`
** The NetCDF-formatted model parameter file, which is read into LIS at runtime. `d01` refers to the indexed domain, typically used as "nests" for NASA-Unified WRF simulations.
* `lislog.0000`
** The output diagnostic file that provides runtime messages, including warnings and error messages. This file is useful for verifying successful run completion and troubleshooting unsuccessful runs.
* `MaskParamFill.log`
** This diagnostic file informs of any disagreements between an LSM-based parameter and the landmask, and whether any parameter gridcells were "filled" to agree with the landmask.

==== The Testcase Domain: Southern Great Plains

In late April of 2017, a major snow storm event occurred across the Southern Great Plains (SGP) and Rocky Mountains, an area spanning Oklahoma and Southern Kansas (see purple box in the map below). This storm event will be the focus of these testcases.

Domain specification:

include::domain_spec.adoc[]